language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DKLF5rDoCzuyV2xwgSV9PfCx4weovv2IRaLU2thWi4/eMVqeM+7KxY2a48rUWrxCZHdMie6SqtfCtugC9wfcR0LE2rC/cmeJvMYE33jQ1pNIaYaW7j1hceKwrOeBMi7VPH6Z4eYdPxOh6mKLwxkZ4ZEaKO5csG1FOJFR9y6whQK1EOeCKFEecl4cI4MXgNZicEQdcoGLWic6tDpE8XcAlpWs2MXyRnmZ8soPVhSf068Wc21ihQHgB9oaMHo3g3QXH1cJKzCg/mMU5ga+SmFBralgnvwn7c7Y+WJamK9G17+4lYQ/YPhKVbvBOvOSJ88YzG3VeMHtwwuUJI4r5vppxA0MOURw6f4X9ZhWdwzSRu3e7pT9qMuv7wA+g4tjp8fNRFAVxO15/cKTMQXPB0MVglkNw7Pbm6xL0uuROkbio9tPM21W1vZFDkeILwJrNAhoaeGNYZa3Lmc3O/Y7KIfpymqQH5jiqJT8sOKWXl6rQTqlGu35UHuRwb2owARxTYM1AvJK4QC8i2+bl8Xld5xszryczvNRyWnDYJ0Png2dJhYL2JUmqm5+FOCeMPtOnYbv6q6uk5ZBslU00BARvnjOhDW8lAJV123wEWo8G09N936uXPfTg4Wx5SoR4Onlds6l+yXinYMQ8Rtg6kFXXu7pPCjH20fNyiYSwYgX+lVawts=
  app: powerful-hollows-25002
  on:
    repo: lkulas/blog-API
